app/forms/feedback.py
from flask_wtf import FlaskForm
from wtforms import (
    SubmitField,
    StringField,
    TextAreaField,
)
from wtforms.validators import Length, Email


class FeedbackForm(FlaskForm):
    feedback_name = StringField(
        "Name",
        validators=[Length(max=15)],
        render_kw={"placeholder": "Your Name"},
    )
    feedback_email = StringField(
        "Email",
        validators=[Email(message="Wrong email format")],
        render_kw={"placeholder": "Email"},
    )
    feedback_message = TextAreaField(
        "Feedback message",
        validators=[Length(max=640)],
        render_kw={"placeholder": ""},
    )

    submit = SubmitField("Leave Feedback")

app/views/auth.py
from flask_mail import Message
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flask_login import login_user, logout_user, login_required, current_user

import app.models as m
from app.forms import LoginForm, RegistrationForm, ForgotPassword, ChangePasswordForm
from app.logger import log
from app import mail
from config import BaseConfig as conf

auth_blueprint = Blueprint("auth", __name__)


@auth_blueprint.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm(request.form)
    if form.validate_on_submit():
        user = m.User(
            username=form.username.data,
            email=form.email.data,
        )
        log(log.INFO, "Create user [%s]", user)
        user.save()

        msg = Message(
            subject="New password",
            sender=conf.MAIL_DEFAULT_SENDER,
            recipients=[user.email],
        )
        url = url_for(
            "auth.password_recovery",
            reset_password_uid=user.reset_password_uid,
            _external=True,
        )

        msg.html = render_template(
            "email/register.html",
            user=user,
            url=url,
            config=conf,
        )
        mail.send(msg)

        flash(
            "Please visit your email address to set you password",
            "success",
        )
        return redirect(url_for("main.index"))
    elif form.is_submitted():
        log(log.ERROR, "The given data was invalid")
        flash("The given data was invalid.", "danger")
    return render_template("auth/register.html", form=form)


@auth_blueprint.route("/login", methods=["GET", "POST"])
def login():
    if not current_user.is_anonymous:
        log(log.INFO, "User [%s] is already logged in", current_user)
        flash("You are already logged in.", "danger")
        return redirect(url_for("main.index"))

    form = LoginForm(request.form)
    if form.validate_on_submit():
        user: m.User = m.User.authenticate(form.email.data, form.password.data)
        if user:
            log(log.INFO, "Login user [%s]", user)
            login_user(user)
            flash("Login successful.", "success")
            return redirect(url_for("main.index"))
        log(log.ERROR, "Wrong email or password")
        flash("Wrong email or password.", "danger")
    return render_template("auth/login.html", form=form)


@auth_blueprint.route("/logout")
@login_required
def logout():
    log(log.INFO, "Logout user [%s]", current_user)
    logout_user()
    flash("You were logged out.", "info")
    return redirect(url_for("main.index"))


@auth_blueprint.route("/reset_password", methods=["GET", "POST"])
def reset_password():
    if current_user.is_authenticated:
        log(log.INFO, "User [%s] in logged in", current_user)
        return redirect(url_for("main.index"))

    form = ForgotPassword()
    if form.validate_on_submit():
        email: str = form.email.data

        # edit previous recovery request
        user: m.User = m.User.query.filter(m.User.email == email.lower()).first()

        if user:
            log(log.INFO, "Create recovery request [%s]", user)
            user.reset_password()

            msg = Message(
                subject="Reset password",
                sender=conf.MAIL_DEFAULT_SENDER,
                recipients=[user.email],
            )
            url = url_for(
                "auth.password_recovery",
                reset_password_uid=user.reset_password_uid,
                _external=True,
            )

            msg.html = render_template(
                "email/reset_password.html",
                user=user,
                url=url,
                config=conf,
            )

            mail.send(msg)
            flash(
                "Password reset successful. For set new password please check your e-mail.",
                "success",
            )
            return redirect(url_for("main.index"))
    elif form.is_submitted():
        flash("No registered user with this e-mail", "danger")
    return render_template("auth/forgot_password.html", form=form)


@auth_blueprint.route(
    "/password_recovery/<reset_password_uid>", methods=["GET", "POST"]
)
def password_recovery(reset_password_uid):
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))

    message = error = None

    user: m.User = m.User.query.filter(
        m.User.reset_password_uid == reset_password_uid
    ).first()

    if not user:
        log(log.ERROR, "wrong reset_password_uid. [%s]", reset_password_uid)
        flash("Incorrect reset password link", "danger")
        return redirect(url_for("main.index"))

    form = ChangePasswordForm()

    if form.validate_on_submit():
        log(log.INFO, "Change password [%s]", user)
        user.password = form.password.data
        user.activated = True
        user.reset_password_uid = ""
        user.save()
        login_user(user)
        flash("Login successful.", "success")
        return redirect(url_for("main.index"))

    return render_template(
        "auth/reset_password.html",
        form=form,
        reset_password_uid=reset_password_uid,
        message=message,
        error=error,
    )

app/views/feedback.py
from flask import Blueprint, render_template, flash
from flask_mail import Message

from app.forms import FeedbackForm
from config import BaseConfig as conf
from app import mail

blueprint = Blueprint("feedback", __name__, url_prefix="/feedback")


@blueprint.route("/", methods=["GET", "POST"])
def feedback():
    form = FeedbackForm()

    if form.validate_on_submit():
        msg = Message(
            subject="New feedback",
            sender=conf.MAIL_DEFAULT_SENDER,
            recipients=[conf.MAIL_FEEDBACK_RECEIVER],
        )

        msg.html = render_template(
            "email/feedback.html",
            feedback_name=form.feedback_name.data,
            feedback_email=form.feedback_email.data,
            feedback_message=form.feedback_message.data,
            config=conf,
        )
        mail.send(msg)

        flash("Feedback sent", "success")
    elif form.is_submitted():
        flash("Invalid data", "danger")

    return render_template("feedback.html", form=form)

app/views/privacy.py
from flask import Blueprint, render_template

blueprint = Blueprint("privacy", __name__, url_prefix="/privacy")


@blueprint.route("/", methods=["GET", "POST"])
def privacy():
    return render_template("privacy.html")

app/views/settings.py
import base64

from flask import jsonify, Blueprint, render_template, flash, request
from flask_login import login_required, current_user

import app.models as m
from app.forms import SettingsForm

blueprint = Blueprint("settings", __name__, url_prefix="/settings")


@blueprint.route("/", methods=["GET", "POST"])
@login_required
def settings():
    form = SettingsForm()

    if form.validate_on_submit():
        current_user.metric_system = m.User.MetricSystem[form.metric_system.data]
        current_user.print_price = form.print_price.data
        current_user.currency = form.currency.data
        current_user.is_price_per_sheet = form.is_price_per.data == "Sheet"
        current_user.moq = form.moq.data
        current_user.cut_spacing = form.cut_spacing.data
        current_user.is_enabled_buy_btn = form.is_enabled_buy_btn.data
        current_user.buy_url = form.buy_url.data
        current_user.shop_name = form.shop_name.data
        if form.logo_img.data:
            img_data = form.logo_img.data.read()
            img_data = base64.b64encode(img_data)
            current_user.logo_img = img_data.decode("utf-8")
        current_user.contact_name = form.contact_name.data
        current_user.contact_email = form.contact_email.data
        current_user.contact_phone = form.contact_phone.data

        current_user.save()
        flash("Updated", "success")
    elif form.is_submitted():
        flash("Invalid data", "danger")

    return render_template("user/settings.html", form=form)


@blueprint.route("/sheet/create", methods=["POST"])
@login_required
def sheet_create():
    data = request.json if request.json else {}

    width = float(data.get("width")) if data.get("width") is not None else None
    height = float(data.get("height")) if data.get("height") is not None else None
    price = float(data.get("price")) if data.get("price") is not None else 0
    moq = int(data.get("moq")) if data.get("moq") not in ["", None] else 1
    use_in_row = (
        bool(data.get("use_in_row")) if data.get("use_in_row") is not None else False
    )

    if width is None or height is None:
        return jsonify({"message": "Width and height are required"}), 400
    elif width <= 0 or height <= 0:
        return jsonify({"message": "Size value cannot be 0 or less"}), 400

    sheet = m.Sheet(
        user=current_user,
        width=width,
        height=height,
        price=price,
        moq=moq,
        use_in_row=use_in_row,
    )
    sheet.save()
    return jsonify({"message": "success", "id": sheet.id})


@blueprint.route("/sheet/delete", methods=["DELETE"])
@login_required
def sheet_delete():
    data = request.json if request.json else {}

    sheet_id = data.get("id")
    if sheet_id is None:
        return jsonify({"message": "id is required"}), 400

    sheet = m.Sheet.query.get(sheet_id)
    if not sheet or sheet.user != current_user:
        return jsonify({"message": "Sheet not found"}), 400

    sheet.delete()

    return jsonify({"message": "success"})

app/views/term.py
from flask import Blueprint, render_template

blueprint = Blueprint("term", __name__, url_prefix="/term")


@blueprint.route("/", methods=["GET", "POST"])
def term():
    return render_template("term.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{{ config.APP_NAME }}</title>
    <!-- meta -->
    <meta name="description" content="" />
    <meta name="author" content="" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    {% block meta %}{% endblock %}

    <link
      href="{{ url_for('static', filename='css/bootstrap/bootstrap.min.css') }}"
      rel="stylesheet"
    />
    <link
      href="{{ url_for('static', filename='css/main.css') }}"
      rel="stylesheet"
      media="screen"
    />
    <link
      href="{{ url_for('static', filename='css/iziToast.min.css') }}"
      rel="stylesheet"
      media="screen"
    />
    {% block links %}{% endblock %}
  </head>

  <body>
    <!-- Header -->
    <header>
      <!-- Navigation -->
      <nav class="navbar navbar-light navbar-expand-md bg-light">
        <div
          class="container d-flex justify-content-center navbar-content align-items-center m-0 mw-100"
        >
          {% if not current_user.is_anonymous %} {% set calculator_url =
          url_for("calculator.calculator", printshop=current_user.shop_name or
          current_user.id) %} {% else %} {% set calculator_url =
          url_for("calculator.calculator") %} {% endif %} {% if img %}
          <div class="mt-3 p-1 logo-div">
            <a
              {%
              if
              order_url
              %}
              href="{{order_url}}"
              target="_blank"
              {%
              endif
              %}
            >
              <img
                class="logo-img"
                src="data:image/jpeg;base64,{{img}}"
                alt="logo"
              />
            </a>
          </div>
          {% endif %}
          <a
            {%
            if
            img
            %}
            class="navbar-brand"
            {%
            else
            %}
            class="navbar-brand-without-img"
            {%
            endif
            %}
            href="{{ calculator_url }}"
            >{{ config.APP_NAME }}</a
          >

          <button
            class="navbar-toggler"
            data-bs-toggle="collapse"
            data-bs-target="#navbar"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div>
            <div class="navbar-collapse collapse" id="navbar">
              <ul class="navbar-nav">
                {% if not current_user.is_anonymous %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('settings.settings') }}"
                    >Settings</a
                  >
                </li>
                {% endif %}
              </ul>
              <!-- Login/Logout -->
              <ul class="navbar-nav ml-auto">
                {% if current_user.is_authenticated %}
                <li class="nav-item dropdown">
                  <a
                    class="nav-link dropdown-toggle"
                    href="#"
                    id="userActions"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false"
                    data-bs-toggle="dropdown"
                    >{{current_user.username | capitalize}}</a
                  >
                  <div
                    class="dropdown-menu border-0 bg-light w-100 border border-top-0 border-secondary"
                    aria-labelledby="userActions"
                  >
                    <a
                      class="dropdown-item opacity-75"
                      href="{{ url_for('auth.logout') }}"
                      >Logout</a
                    >
                  </div>
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.login') }}"
                    >Login</a
                  >
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{{ url_for('auth.register') }}"
                    >Register</a
                  >
                </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <!-- Flash Messages -->
    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %}
    <div
      class="hit_flash d-flex justify-content-between alert alert-{{ category }} alert-dismisible"
    >
      <div></div>
      <p>{{ message }}</p>
      <div class="flash_inner">
        <button
          type="button"
          class="close d-flex justify-content-center align-items-center me-3"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
    {% endfor %} {% endif %} {% endwith %}

    <!-- Main Content -->
    <div class="main-content"> {% block content %}{% endblock %}</div>
   

    <!-- Footer-->

    <!-- scripts -->
    <script src="{{ url_for('static', filename='js/bootstrap/bootstrap.bundle.min.js') }}"></script>
    <script
      src="{{ url_for('static', filename='js/main.js') }}"
      type="text/javascript"
      defer
    ></script>
    <script
      src="{{ url_for('static', filename='js/iziToast.min.js') }}"
      type="text/javascript"
      defer
    ></script>
    {% block scripts %}{% endblock %}

    <footer class="footer">
      <div class="p-3">
        <div class="row text-center justify-content-between">
          <div class="col-lg-3">
            <a class="mb-3 footer-link" href="{{ url_for('privacy.privacy') }}"
              >Privacy Policy</a
            >
          </div>
          <div class="col-lg-3">
            <a class="mb-3 footer-link" href="{{ url_for('term.term') }}"
              >Terms & Conditions</a
            >
          </div>
          <div class="col-lg-3">
            <a
              class="mb-3 footer-link"
              href="{{ url_for('feedback.feedback') }}"
              >Have Feedback?</a
            >
          </div>
        </div>
      </div>
      <div class="text-center w-100 footer-bottom">
        <div id="current_date">
          <script src="{{ url_for('static', filename='js/date.js') }}"></script>
        </div>
      </div>
    </footer>
  </body>
</html>

app/templates/error.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron my-4">
  <div class="text-center">
    <h1>{{ '%s - %s' % (error.code, error.name) }}</h1>
    <p>{{ error.description }}.</p>
  </div>
</div>
{% endblock %}

app/templates/feedback.html
{% extends 'base.html' %} {% block content %}
<div class="pb-100px h-100">
  <div class="container py-4">
    <h3 class="text-center">Feedback</h3>
    <div class="d-flex justify-content-center">
      <div class="feedback-form p2 w-75">
        <div class="card-body">
          <form
            class="form"
            role="form"
            action="{{ url_for('feedback.feedback') }}"
            method="post"
          >
            <div class="mb-3">
              <label for="feedback_name" class="form-label"
                >{{form.feedback_name.label}}</label
              >
              {{form.feedback_name(class="form-control", id="feedback_name",
              value=current_user.feedback_name if current_user.feedback_name
              else "")}} {% for error in form.errors.feedback_name %}
              <small class="text-danger">{{error}}</small> {% endfor %}
            </div>

            <div class="mb-3">
              <label for="feedback_email" class="form-label"
                >{{form.feedback_email.label}}</label
              >
              {{form.feedback_email(class="form-control", id="feedback_email",
              value=current_user.feedback_email if current_user.feedback_email
              else "")}} {% for error in form.errors.feedback_email %}
              <small class="text-danger">{{error}}</small> {% endfor %}
            </div>

            <div class="mb-3">
              <label for="feedback_message" class="form-label"
                >{{form.feedback_message.label}}</label
              >
              {{form.feedback_message(class="form-control",
              id="feedback_message", value=current_user.feedback_message if
              current_user.feedback_message else "")}} {% for error in
              form.errors.feedback_message %}
              <small class="text-danger">{{error}}</small> {% endfor %}
            </div>

            {{ form.submit(class="form-control btn btn-success rounded" ) }}
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block content %}
<div class="container"></div>
{% endblock %}